services:
  frontend:
    build:
      context: ./
      # platform: linux/amd64  # Force x64 architecture

    restart: always
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
  
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - next
